sudo: required

language: bash

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.6.2

before_install:
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" -y install docker-engine

install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build php-base php-tests-with-report

script:
  - >
    docker-compose run
    --rm
    -e CODECLIMATE_REPO_TOKEN=$CODECLIMATE_REPO_TOKEN
    php-tests-with-report

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

notifications:
  slack:
    secure: ChvN4480tvXkv3Vf1G7cQ/eSS6uGnQwJwxDzGJ52XA2zIc6LOV0iypgyF7TaLBqQWZ/7490FeQ6S5pEFSkHUI9web1SLgW18pw4dtQIt0QOC8jW8D1eH7qVtCkhqbMxuJwJqUk6qrkoOVg9oD6D/PYKZWCXLTLxNBJssgFmX9hrIfAeOiybOlAs478RZZMRM6RPFoad7UAMkZxnyxbtYU5wNts4YH0LbpafofR5ufEd36nd98hHZ7v+eOMj+dycQK2z49u3UhY/tHMDvhC0NA7YCylW2IsP3shShFh04BnuKfeCz6RstcGHtiN2DJcO4A9ga04drT/xrl7GMv+lJNvVtDIm/EMVm6Hhrhkv28QGRBO1azGceRs9ROT8TJF7EgCd7CKuLBVBrL+mmqcizbtd5w9N9uUbm2B65SO21o+/1N6/H5My/ihcywDy4g6M7JbpmxY17Z+UkUgS4/VB6MewMsRDrSXV2kvwCjYd63rV46FuxMTD02t+xscS0qX7J7XtClaJzAUzF6NyevsTEpZG8Zj9WTAH56XgfkMzh5fw8ZT+/mEdqoBCBG5Frsz9Rkye3004GSOzE/i1Db5Ts04EmCBc6ZPsWX3fprPHkDDmIhZCTFNk/Vy6LLdHNZK1EZ8h8khCLPtEGxmnI4u8FVd/cDGkAizx8amhxsho3mr4=
