sudo: required

env:
  global:
    - DP_VENDOR_ID="keboola"
    - DP_APP_ID="keboola.ex-mongodb"

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker-compose -v
  - set -e

after_success:
  - docker images

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true

jobs:
  include:
  - stage: build and test
    script:
    - docker-compose build php
    - docker-compose build php-tests-with-report
    - >-
      docker-compose run
      --rm
      -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
      -e GIT_COMMIT_SHA=$TRAVIS_COMMIT
      -e GIT_BRANCH=$TRAVIS_BRANCH
      php-tests-with-report
    if: branch != master AND NOT tag IS present

  - stage: build, test and push
    script:
    - docker pull quay.io/keboola/developer-portal-cli-v2:latest
    - docker-compose build php
    - docker-compose build php-tests-with-report
    - >-
      docker-compose run
      --rm
      -e CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID
      -e GIT_COMMIT_SHA=$TRAVIS_COMMIT
      -e GIT_BRANCH=$TRAVIS_BRANCH
      php-tests-with-report
    - >-
      export REPOSITORY=`docker run --rm
      -e KBC_DEVELOPERPORTAL_USERNAME
      -e KBC_DEVELOPERPORTAL_PASSWORD
      quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $DP_VENDOR_ID $DP_APP_ID`
    - docker tag keboola/mongodb-extractor $REPOSITORY:$TRAVIS_BRANCH
    - >-
      eval $(docker run --rm
      -e KBC_DEVELOPERPORTAL_USERNAME
      -e KBC_DEVELOPERPORTAL_PASSWORD
      quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $DP_VENDOR_ID $DP_APP_ID)
    - docker push $REPOSITORY:$TRAVIS_BRANCH
    if: branch = master OR tag IS present

  - stage: run test job
    script:
      - docker pull quay.io/keboola/syrup-cli:latest
      - >-
        docker run
        --rm
        -e KBC_STORAGE_TOKEN
        quay.io/keboola/syrup-cli:latest run-job $DP_APP_ID 321622942 $TRAVIS_BRANCH
    if: branch = master OR tag IS present

  - stage: pull image, tag and deploy
    script:
    - docker pull quay.io/keboola/developer-portal-cli-v2:latest
    - >-
      eval $(docker run --rm
      -e KBC_DEVELOPERPORTAL_USERNAME
      -e KBC_DEVELOPERPORTAL_PASSWORD
      quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $DP_VENDOR_ID $DP_APP_ID)
    - >-
      export REPOSITORY=`docker run --rm
      -e KBC_DEVELOPERPORTAL_USERNAME
      -e KBC_DEVELOPERPORTAL_PASSWORD
      quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $DP_VENDOR_ID $DP_APP_ID`
    - docker pull $REPOSITORY:$TRAVIS_BRANCH
    - docker tag $REPOSITORY:$TRAVIS_BRANCH $REPOSITORY:$TRAVIS_TAG
    - docker push $REPOSITORY:$TRAVIS_TAG
    - >-
      docker run --rm
      -e KBC_DEVELOPERPORTAL_USERNAME
      -e KBC_DEVELOPERPORTAL_PASSWORD
      quay.io/keboola/developer-portal-cli-v2:latest update-app-repository $DP_VENDOR_ID $DP_APP_ID $TRAVIS_TAG
    if: tag IS present

notifications:
  slack:
    secure: ChvN4480tvXkv3Vf1G7cQ/eSS6uGnQwJwxDzGJ52XA2zIc6LOV0iypgyF7TaLBqQWZ/7490FeQ6S5pEFSkHUI9web1SLgW18pw4dtQIt0QOC8jW8D1eH7qVtCkhqbMxuJwJqUk6qrkoOVg9oD6D/PYKZWCXLTLxNBJssgFmX9hrIfAeOiybOlAs478RZZMRM6RPFoad7UAMkZxnyxbtYU5wNts4YH0LbpafofR5ufEd36nd98hHZ7v+eOMj+dycQK2z49u3UhY/tHMDvhC0NA7YCylW2IsP3shShFh04BnuKfeCz6RstcGHtiN2DJcO4A9ga04drT/xrl7GMv+lJNvVtDIm/EMVm6Hhrhkv28QGRBO1azGceRs9ROT8TJF7EgCd7CKuLBVBrL+mmqcizbtd5w9N9uUbm2B65SO21o+/1N6/H5My/ihcywDy4g6M7JbpmxY17Z+UkUgS4/VB6MewMsRDrSXV2kvwCjYd63rV46FuxMTD02t+xscS0qX7J7XtClaJzAUzF6NyevsTEpZG8Zj9WTAH56XgfkMzh5fw8ZT+/mEdqoBCBG5Frsz9Rkye3004GSOzE/i1Db5Ts04EmCBc6ZPsWX3fprPHkDDmIhZCTFNk/Vy6LLdHNZK1EZ8h8khCLPtEGxmnI4u8FVd/cDGkAizx8amhxsho3mr4=
  email: false
