version: "2"

services:

  php-base:
    build: .
    image: keboola/mongodb-extractor

  php:
    extends:
      service: php-base
    tty: true
    stdin_open: true
    links:
      - mongodb
    command: bash

  php-tests:
    extends:
      service: php-base
    links:
      - mongodb
    command: >
             sh -c '
             sleep 4
             && mongoimport --host mongodb --db test --collection restaurants --drop
             --file tests/dataset.json
             && ./tests.sh
             '

  php-tests-with-report:
    extends:
      service: php-base
    links:
      - mongodb
    volumes:
      - ./.git:/code/.git
    command: >
             sh -c '
             sleep 4
             && mongoimport --host mongodb --db test --collection restaurants --drop
             --file tests/dataset.json
             && ./tests.sh
             && ./vendor/bin/test-reporter
             '

  mongodb:
    build: docker/mongodb
