version: "2"

services:

  php:
    build: .
    image: keboola/mongodb-extractor
    tty: true
    stdin_open: true
    links:
      - mongodb
      - mongodb-ssh
      - mongodb-auth
      - mongodb-auth-ssh
    command: >
             sh -c '
             sleep 4
             && mongoimport --host mongodb --db test --collection restaurants --drop --file tests/dataset.json
             && mongoimport --host mongodb-auth --username user --password user --db test --collection restaurants --drop --file tests/dataset.json
             && bash
             '
    volumes:
      - ./:/code

  php-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - mongodb
      - mongodb-ssh
      - mongodb-auth
      - mongodb-auth-ssh
    command: >
             sh -c '
             sleep 4
             && mongoimport --host mongodb --db test --collection restaurants --drop --file tests/dataset.json
             && mongoimport --host mongodb-auth --username user --password user --db test --collection restaurants --drop --file tests/dataset.json
             && ./tests.sh
             '

  php-tests-with-report:
    build:
      context: .
      dockerfile: Dockerfile-tests
    links:
      - mongodb
      - mongodb-ssh
      - mongodb-auth
      - mongodb-auth-ssh
    volumes:
      - ./.git:/code/.git
    command: >
             sh -c '
             sleep 4
             && mongoimport --host mongodb --db test --collection restaurants --drop --file tests/dataset.json
             && mongoimport --host mongodb-auth --username user --password user --db test --collection restaurants --drop --file tests/dataset.json
             && ./tests.sh
             && ./vendor/bin/test-reporter
             '

  mongodb:
    image: mongo:3.2

  mongodb-auth:
    extends:
      service: mongodb
    volumes:
      - ./docker/mongodb/init.js:/init.js
    command: >
             sh -c '
             sh -c "mongod &"
             && sleep 2
             && mongo < /init.js
             && mongod --shutdown
             && mongod --auth
             '

  mongodb-ssh:
    build: ./docker/ssh
    links:
      - mongodb:mongodb-behind-ssh

  mongodb-auth-ssh:
    build: ./docker/ssh
    links:
      - mongodb-auth:mongodb-auth-behind-ssh
